import {
  buildNormalizedScanDraftComponents,
  buildNormalizedScanDraftItems,
  createEmptyNutrition,
  createAiEstimatedDraftItem,
  createUsdaDraftItem,
  findBestUsdaMatch,
  groupAssembledFoodDraftItems,
  mergeDuplicateStandaloneDraftItems,
  scaleDraftItem,
} from "../../lib/domain/scan";

describe("scan domain helpers", () => {
  it("drops invalid items and merges duplicate normalized names", () => {
    const items = buildNormalizedScanDraftItems([
      {
        confidence: "medium",
        estimatedGrams: 150,
        name: "Grilled Chicken Breast",
        nutrition: {
          b12: 0.2,
          b6: 0.6,
          calcium: 12,
          calories: 248,
          carbs: 0,
          choline: 55,
          copper: 0.2,
          fat: 5.4,
          fiber: 0,
          folate: 4,
          iron: 1,
          magnesium: 32,
          manganese: 0.3,
          niacin: 12,
          omega3: 0.2,
          phosphorus: 210,
          potassium: 256,
          protein: 46,
          riboflavin: 0.1,
          selenium: 18,
          sodium: 104,
          sugar: 0,
          thiamin: 0.1,
          vitaminA: 14,
          vitaminC: 0,
          vitaminD: 0.1,
          vitaminE: 0.3,
          vitaminK: 0.5,
          zinc: 1,
        },
        portionLabel: "1 grilled breast",
        prepMethod: "grilled",
      },
      {
        confidence: "high",
        estimatedGrams: 55,
        name: " grilled chicken breast ",
        nutrition: {
          b12: 0.1,
          b6: 0.2,
          calcium: 4,
          calories: 90,
          carbs: 0,
          choline: 22,
          copper: 0.1,
          fat: 2.1,
          fiber: 0,
          folate: 1,
          iron: 0.3,
          magnesium: 10,
          manganese: 0.4,
          niacin: 4,
          omega3: 0.3,
          phosphorus: 74,
          potassium: 91,
          protein: 17,
          riboflavin: 0.05,
          selenium: 12,
          sodium: 36,
          sugar: 0,
          thiamin: 0.03,
          vitaminA: 5,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.1,
          vitaminK: 0.2,
          zinc: 0.4,
        },
        portionLabel: "extra slices",
        prepMethod: "grilled",
      },
      {
        confidence: "low",
        estimatedGrams: 0,
        name: "Mystery sauce",
        nutrition: {
          b12: 0,
          b6: 0,
          calcium: 0,
          calories: 40,
          carbs: 8,
          choline: 0,
          copper: 0,
          fat: 0,
          fiber: 0,
          folate: 0,
          iron: 0,
          magnesium: 0,
          manganese: 0,
          niacin: 0,
          omega3: 0,
          phosphorus: 0,
          potassium: 0,
          protein: 0,
          riboflavin: 0,
          selenium: 0,
          sodium: 180,
          sugar: 6,
          thiamin: 0,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0,
          vitaminK: 0,
          zinc: 0,
        },
        portionLabel: "a drizzle",
        prepMethod: undefined,
      },
    ]);

    expect(items).toHaveLength(1);
    expect(items[0]).toEqual(
      expect.objectContaining({
        confidence: "high",
        estimatedGrams: 205,
        name: "Grilled Chicken Breast",
        prepMethod: "grilled",
        source: "ai_estimated",
      })
    );
    expect(items[0].nutrition).toEqual(
      expect.objectContaining({
        calories: 338,
        choline: 77,
        copper: 0.3,
        fat: 7,
        manganese: 0.7,
        omega3: 0.5,
        protein: 63,
        selenium: 30,
      })
    );
  });

  it("chooses a strong USDA match but rejects weak ones", () => {
    const candidates = [
      {
        caloriesPer100g: 165,
        category: "protein",
        fdcId: "1001",
        name: "Chicken, broilers or fryers, breast, meat only, cooked, grilled",
      },
      {
        caloriesPer100g: 237,
        category: "protein",
        fdcId: "1002",
        name: "Chicken, broilers or fryers, breast, meat only, fried",
      },
      {
        caloriesPer100g: 130,
        category: "grains",
        fdcId: "1003",
        name: "Rice, white, cooked",
      },
    ];

    expect(findBestUsdaMatch("grilled chicken breast", candidates)?.fdcId).toBe("1001");
    expect(findBestUsdaMatch("orange chicken", candidates)).toBeNull();
  });

  it("recalculates USDA and AI-estimated items from the multiplier", () => {
    const usdaItem = createUsdaDraftItem({
      confidence: "high",
      estimatedGrams: 120,
      name: "White rice",
      nutrition: {
        b12: 0,
        b6: 0.1,
        calcium: 10,
        calories: 156,
        carbs: 33.6,
        choline: 12,
        copper: 0.04,
        fat: 0.4,
        fiber: 0.5,
        folate: 58,
        iron: 0.2,
        magnesium: 14,
        manganese: 0.3,
        niacin: 1.7,
        omega3: 0.2,
        phosphorus: 52,
        potassium: 42,
        protein: 3.2,
        riboflavin: 0.02,
        selenium: 7,
        sodium: 2,
        sugar: 0.1,
        thiamin: 0.02,
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        zinc: 0.6,
      },
      per100g: {
        b12: 0,
        b6: 0.08,
        calcium: 8,
        calories: 130,
        carbs: 28,
        choline: 10,
        copper: 0.03,
        fat: 0.3,
        fiber: 0.4,
        folate: 48,
        iron: 0.17,
        magnesium: 12,
        manganese: 0.2,
        niacin: 1.4,
        omega3: 0.1,
        phosphorus: 43,
        potassium: 35,
        protein: 2.7,
        riboflavin: 0.02,
        selenium: 6,
        sodium: 1.6,
        sugar: 0.08,
        thiamin: 0.02,
        vitaminA: 0,
        vitaminC: 0,
        vitaminD: 0,
        vitaminE: 0,
        vitaminK: 0,
        zinc: 0.5,
      },
      portionLabel: "1 bowl",
      usdaFoodId: "1003",
    });
    const aiItem = createAiEstimatedDraftItem({
      confidence: "medium",
      estimatedGrams: 180,
      name: "Chicken bowl",
      nutrition: {
        b12: 0.2,
        b6: 0.4,
        calcium: 40,
        calories: 620,
        carbs: 58,
        choline: 210,
        copper: 0.4,
        fat: 18,
        fiber: 6,
        folate: 90,
        iron: 3,
        magnesium: 60,
        manganese: 0.9,
        niacin: 8,
        omega3: 0.7,
        phosphorus: 200,
        potassium: 520,
        protein: 42,
        riboflavin: 0.2,
        selenium: 32,
        sodium: 780,
        sugar: 5,
        thiamin: 0.15,
        vitaminA: 80,
        vitaminC: 12,
        vitaminD: 0,
        vitaminE: 0.8,
        vitaminK: 8,
        zinc: 2.2,
      },
      portionLabel: "1 entree",
      prepMethod: "mixed",
    });

    const scaledUsda = scaleDraftItem(usdaItem, 1.5);
    const scaledAi = scaleDraftItem(aiItem, 0.5);

    expect(scaledUsda.estimatedGrams).toBe(180);
    expect(scaledUsda.nutrition).toEqual(
      expect.objectContaining({
        calories: 234,
        choline: 18,
        carbs: 50,
        copper: 0.1,
        manganese: 0.4,
        omega3: 0.2,
        protein: 5,
        selenium: 11,
      })
    );

    expect(scaledAi.estimatedGrams).toBe(90);
    expect(scaledAi.nutrition).toEqual(
      expect.objectContaining({
        calories: 310,
        carbs: 29,
        choline: 105,
        copper: 0.2,
        manganese: 0.5,
        omega3: 0.4,
        protein: 21,
        selenium: 16,
      })
    );
  });

  it("groups obvious sandwich components into one assembled draft item", () => {
    const components = buildNormalizedScanDraftComponents([
      {
        confidence: "high",
        estimatedGrams: 28,
        name: "Whole grain sandwich bread",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 26,
          calories: 74,
          carbs: 13,
          choline: 12,
          copper: 0.1,
          fat: 1,
          fiber: 2,
          folate: 24,
          iron: 0.7,
          magnesium: 18,
          manganese: 0.4,
          niacin: 1.8,
          omega3: 0,
          phosphorus: 42,
          potassium: 66,
          protein: 4,
          riboflavin: 0.05,
          selenium: 9,
          sodium: 132,
          sugar: 2,
          thiamin: 0.2,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.2,
          vitaminK: 0.5,
          zinc: 0.5,
        },
        portionLabel: "1 slice",
      },
      {
        confidence: "high",
        estimatedGrams: 28,
        name: "Whole grain sandwich bread",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 26,
          calories: 74,
          carbs: 13,
          choline: 12,
          copper: 0.1,
          fat: 1,
          fiber: 2,
          folate: 24,
          iron: 0.7,
          magnesium: 18,
          manganese: 0.4,
          niacin: 1.8,
          omega3: 0,
          phosphorus: 42,
          potassium: 66,
          protein: 4,
          riboflavin: 0.05,
          selenium: 9,
          sodium: 132,
          sugar: 2,
          thiamin: 0.2,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.2,
          vitaminK: 0.5,
          zinc: 0.5,
        },
        portionLabel: "1 slice",
      },
      {
        confidence: "medium",
        estimatedGrams: 16,
        name: "Peanut butter spread inside sandwich",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 8,
          calories: 94,
          carbs: 3,
          choline: 18,
          copper: 0.1,
          fat: 8,
          fiber: 1,
          folate: 12,
          iron: 0.3,
          magnesium: 27,
          manganese: 0.2,
          niacin: 2,
          omega3: 0.1,
          phosphorus: 55,
          potassium: 104,
          protein: 4,
          riboflavin: 0.03,
          selenium: 1,
          sodium: 68,
          sugar: 1,
          thiamin: 0.03,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.7,
          vitaminK: 0,
          zinc: 0.4,
        },
        portionLabel: "inside sandwich",
      },
      {
        confidence: "medium",
        estimatedGrams: 14,
        name: "Peanut butter spread inside sandwich",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 7,
          calories: 82,
          carbs: 3,
          choline: 15,
          copper: 0.1,
          fat: 7,
          fiber: 1,
          folate: 10,
          iron: 0.2,
          magnesium: 23,
          manganese: 0.2,
          niacin: 1.7,
          omega3: 0.1,
          phosphorus: 48,
          potassium: 91,
          protein: 4,
          riboflavin: 0.02,
          selenium: 1,
          sodium: 60,
          sugar: 1,
          thiamin: 0.03,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.6,
          vitaminK: 0,
          zinc: 0.3,
        },
        portionLabel: "inside sandwich",
      },
      {
        confidence: "medium",
        estimatedGrams: 18,
        name: "Jelly spread inside sandwich",
        nutrition: {
          b12: 0,
          b6: 0,
          calcium: 3,
          calories: 48,
          carbs: 13,
          choline: 1,
          copper: 0,
          fat: 0,
          fiber: 0,
          folate: 0,
          iron: 0.1,
          magnesium: 2,
          manganese: 0,
          niacin: 0,
          omega3: 0,
          phosphorus: 3,
          potassium: 18,
          protein: 0,
          riboflavin: 0,
          selenium: 0,
          sodium: 10,
          sugar: 10,
          thiamin: 0,
          vitaminA: 0,
          vitaminC: 2,
          vitaminD: 0,
          vitaminE: 0,
          vitaminK: 0,
          zinc: 0,
        },
        portionLabel: "inside sandwich",
      },
    ]);

    const grouped = groupAssembledFoodDraftItems(components);

    expect(grouped).toHaveLength(1);
    expect(grouped[0]).toEqual(
      expect.objectContaining({
        estimatedGrams: 104,
        multiplier: 1,
        name: "Peanut butter and jelly sandwich",
        normalizedName: "peanut butter and jelly sandwich",
        portionLabel: "1 sandwich",
        source: "ai_estimated",
      })
    );
    expect(grouped[0].baseEstimatedGrams).toBe(104);
    expect(grouped[0].baseNutrition).toEqual(grouped[0].nutrition);
    expect(grouped[0].nutrition).toEqual(
      expect.objectContaining({
        calories: 372,
        carbs: 45,
        fat: 17,
        protein: 16,
      })
    );
  });

  it("does not collapse multi-serving sandwich components into one sandwich", () => {
    const components = buildNormalizedScanDraftComponents([
      {
        confidence: "high",
        estimatedGrams: 28,
        name: "Whole grain sandwich bread",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 26,
          calories: 74,
          carbs: 13,
          choline: 12,
          copper: 0.1,
          fat: 1,
          fiber: 2,
          folate: 24,
          iron: 0.7,
          magnesium: 18,
          manganese: 0.4,
          niacin: 1.8,
          omega3: 0,
          phosphorus: 42,
          potassium: 66,
          protein: 4,
          riboflavin: 0.05,
          selenium: 9,
          sodium: 132,
          sugar: 2,
          thiamin: 0.2,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.2,
          vitaminK: 0.5,
          zinc: 0.5,
        },
        portionLabel: "1 slice",
      },
      {
        confidence: "high",
        estimatedGrams: 28,
        name: "Whole grain sandwich bread",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 26,
          calories: 74,
          carbs: 13,
          choline: 12,
          copper: 0.1,
          fat: 1,
          fiber: 2,
          folate: 24,
          iron: 0.7,
          magnesium: 18,
          manganese: 0.4,
          niacin: 1.8,
          omega3: 0,
          phosphorus: 42,
          potassium: 66,
          protein: 4,
          riboflavin: 0.05,
          selenium: 9,
          sodium: 132,
          sugar: 2,
          thiamin: 0.2,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.2,
          vitaminK: 0.5,
          zinc: 0.5,
        },
        portionLabel: "1 slice",
      },
      {
        confidence: "high",
        estimatedGrams: 28,
        name: "Whole grain sandwich bread",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 26,
          calories: 74,
          carbs: 13,
          choline: 12,
          copper: 0.1,
          fat: 1,
          fiber: 2,
          folate: 24,
          iron: 0.7,
          magnesium: 18,
          manganese: 0.4,
          niacin: 1.8,
          omega3: 0,
          phosphorus: 42,
          potassium: 66,
          protein: 4,
          riboflavin: 0.05,
          selenium: 9,
          sodium: 132,
          sugar: 2,
          thiamin: 0.2,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.2,
          vitaminK: 0.5,
          zinc: 0.5,
        },
        portionLabel: "1 slice",
      },
      {
        confidence: "high",
        estimatedGrams: 28,
        name: "Whole grain sandwich bread",
        nutrition: {
          b12: 0,
          b6: 0.1,
          calcium: 26,
          calories: 74,
          carbs: 13,
          choline: 12,
          copper: 0.1,
          fat: 1,
          fiber: 2,
          folate: 24,
          iron: 0.7,
          magnesium: 18,
          manganese: 0.4,
          niacin: 1.8,
          omega3: 0,
          phosphorus: 42,
          potassium: 66,
          protein: 4,
          riboflavin: 0.05,
          selenium: 9,
          sodium: 132,
          sugar: 2,
          thiamin: 0.2,
          vitaminA: 0,
          vitaminC: 0,
          vitaminD: 0,
          vitaminE: 0.2,
          vitaminK: 0.5,
          zinc: 0.5,
        },
        portionLabel: "1 slice",
      },
      {
        confidence: "medium",
        estimatedGrams: 16,
        name: "Peanut butter spread inside sandwich",
        nutrition: {
          ...{
            b12: 0, b6: 0.1, calcium: 8, calories: 94, carbs: 3, choline: 18, copper: 0.1,
            fat: 8, fiber: 1, folate: 12, iron: 0.3, magnesium: 27, manganese: 0.2, niacin: 2,
            omega3: 0.1, phosphorus: 55, potassium: 104, protein: 4, riboflavin: 0.03, selenium: 1,
            sodium: 68, sugar: 1, thiamin: 0.03, vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.7, vitaminK: 0, zinc: 0.4,
          },
        },
        portionLabel: "inside sandwich",
      },
      {
        confidence: "medium",
        estimatedGrams: 16,
        name: "Peanut butter spread inside sandwich",
        nutrition: {
          ...{
            b12: 0, b6: 0.1, calcium: 8, calories: 94, carbs: 3, choline: 18, copper: 0.1,
            fat: 8, fiber: 1, folate: 12, iron: 0.3, magnesium: 27, manganese: 0.2, niacin: 2,
            omega3: 0.1, phosphorus: 55, potassium: 104, protein: 4, riboflavin: 0.03, selenium: 1,
            sodium: 68, sugar: 1, thiamin: 0.03, vitaminA: 0, vitaminC: 0, vitaminD: 0, vitaminE: 0.7, vitaminK: 0, zinc: 0.4,
          },
        },
        portionLabel: "inside sandwich",
      },
      {
        confidence: "medium",
        estimatedGrams: 18,
        name: "Jelly spread inside sandwich",
        nutrition: {
          ...{
            b12: 0, b6: 0, calcium: 3, calories: 48, carbs: 13, choline: 1, copper: 0,
            fat: 0, fiber: 0, folate: 0, iron: 0.1, magnesium: 2, manganese: 0, niacin: 0,
            omega3: 0, phosphorus: 3, potassium: 18, protein: 0, riboflavin: 0, selenium: 0,
            sodium: 10, sugar: 10, thiamin: 0, vitaminA: 0, vitaminC: 2, vitaminD: 0, vitaminE: 0, vitaminK: 0, zinc: 0,
          },
        },
        portionLabel: "inside sandwich",
      },
      {
        confidence: "medium",
        estimatedGrams: 18,
        name: "Jelly spread inside sandwich",
        nutrition: {
          ...{
            b12: 0, b6: 0, calcium: 3, calories: 48, carbs: 13, choline: 1, copper: 0,
            fat: 0, fiber: 0, folate: 0, iron: 0.1, magnesium: 2, manganese: 0, niacin: 0,
            omega3: 0, phosphorus: 3, potassium: 18, protein: 0, riboflavin: 0, selenium: 0,
            sodium: 10, sugar: 10, thiamin: 0, vitaminA: 0, vitaminC: 2, vitaminD: 0, vitaminE: 0, vitaminK: 0, zinc: 0,
          },
        },
        portionLabel: "inside sandwich",
      },
    ]);

    const grouped = groupAssembledFoodDraftItems(components);

    expect(grouped.some((item) => item.name === "Peanut butter and jelly sandwich")).toBe(false);
    expect(grouped.length).toBeGreaterThan(1);
  });

  it("does not globally merge already-assembled sandwich items", () => {
    const sandwichOne = createAiEstimatedDraftItem({
      confidence: "high",
      estimatedGrams: 96,
      name: "Peanut butter and jelly sandwich",
      nutrition: {
        ...createEmptyNutrition(),
        calories: 350,
        carbs: 44,
        fat: 15,
        protein: 13,
      },
      portionLabel: "1 sandwich",
    });
    const sandwichTwo = createAiEstimatedDraftItem({
      confidence: "medium",
      estimatedGrams: 98,
      name: "Peanut butter and jelly sandwich",
      nutrition: {
        ...createEmptyNutrition(),
        calories: 360,
        carbs: 45,
        fat: 16,
        protein: 14,
      },
      portionLabel: "1 sandwich",
    });

    const merged = mergeDuplicateStandaloneDraftItems([sandwichOne, sandwichTwo]);

    expect(merged).toHaveLength(2);
    expect(merged.map((item) => item.name)).toEqual([
      "Peanut butter and jelly sandwich",
      "Peanut butter and jelly sandwich",
    ]);
  });
});
